include: 'https://gitlab.com/mateuszwojt/ci-templates/raw/main/.build-and-release-nuke-plugin.yml'

build:linux:
  stage: build
  before_script:
    - cd /tmp
    - wget -q -P /tmp/ https://github.com/OpenImageDenoise/oidn/releases/download/v2.1.0/oidn-2.1.0.x86_64.linux.tar.gz
    - mkdir -p /opt
    - tar -C /opt -xvzf /tmp/oidn-2.1.0.x86_64.linux.tar.gz
    - rm -rf /tmp/oidn-2.1.0.x86_64.linux.tar.gz
  script:
    - cd $CI_PROJECT_DIR
    - mkdir build && cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DOIDN_ROOT=/opt/oidn-2.1.0.x86_64.linux ..
    - make
    - tar -cvzf ${PLUGIN_RELEASE_NAME_LINUX}-${NUKE_VERSION}.tar.gz src/${PLUGIN_NAME}.so menu.py && cd ..

build:macos:
  stage: build
  script:
    - brew install open-image-denoise
    - cd $CI_PROJECT_DIR
    - mkdir build && cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release ..
    - make
    - tar -cvzf ${PLUGIN_RELEASE_NAME_LINUX}-${NUKE_VERSION}.tar.gz src/${PLUGIN_NAME}.so menu.py && cd ..

build:windows:
  stage: build
  script:
    - Invoke-WebRequest -Uri "https://thefoundry.s3.amazonaws.com/products/nuke/releases/15.0v2/Nuke15.0v2-win-x86_64.zip" -OutFile "C:\Nuke15.0v2-win-x86_64.zip"
    - Expand-Archive "C:\Nuke15.0v2-win-x86_64.zip" -DestinationPath "C:\Nuke15.0v2-win-x86_64"
    - cd "C:\Nuke15.0v2-win-x86_64"
    - .\Nuke15.0v2-win-x86_64.exe /S /ACCEPT-FOUNDRY-EULA
    - Invoke-WebRequest -Uri "https://github.com/OpenImageDenoise/oidn/releases/download/v2.1.0/oidn-2.1.0.x64.windows.zip" -OutFile "C:\oidn-2.1.0.x64.windows.zip"
    - Expand-Archive "C:\oidn-2.1.0.x64.windows.zip" -DestinationPath "C:\" -Verbose
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 16 2019" -DOIDN_ROOT="C:\oidn-2.1.0.x64.windows" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release
    - cd ..